In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [54]:
def GenDataset(df):
    ratings_split = df['ratings'].str.split(';', expand=True)
    df_overall=df[['member_id','hotel_id']]
    df_overall.insert(loc=2,column="rating",value=ratings_split[0])
    df_overall["rating"]=pd.to_numeric(df_overall["rating"].str.split(":").str[0])
    df_overall=pd.pivot(df_overall,index="member_id",columns="hotel_id",values="rating")

    df_value=df[['member_id','hotel_id']]
    df_value.insert(loc=2,column="rating",value=ratings_split[1])
    df_value["rating"]=pd.to_numeric(df_value["rating"].str.split(":").str[0])
    df_value=pd.pivot(df_value,index="member_id",columns="hotel_id",values="rating")

    df_location=df[['member_id','hotel_id']]
    df_location.insert(loc=2,column="rating",value=ratings_split[2])
    df_location["rating"]=pd.to_numeric(df_location["rating"].str.split(":").str[0])
    df_location=pd.pivot(df_location,index="member_id",columns="hotel_id",values="rating")


    df_sleep_quality=df[['member_id','hotel_id']]
    df_sleep_quality.insert(loc=2,column="rating",value=ratings_split[3])
    df_sleep_quality["rating"]=pd.to_numeric(df_sleep_quality["rating"].str.split(":").str[0])
    df_sleep_quality=pd.pivot(df_sleep_quality,index="member_id",columns="hotel_id",values="rating")

    df_rooms=df[['member_id','hotel_id']]
    df_rooms.insert(loc=2,column="rating",value=ratings_split[4])
    df_rooms["rating"]=pd.to_numeric(df_rooms["rating"].str.split(":").str[0])
    df_rooms=pd.pivot(df_rooms,index="member_id",columns="hotel_id",values="rating")

    df_Cleanliness=df[['member_id','hotel_id']]
    df_Cleanliness.insert(loc=2,column="rating",value=ratings_split[5])
    df_Cleanliness["rating"]=pd.to_numeric(df_Cleanliness["rating"].str.split(":").str[0])
    df_Cleanliness=pd.pivot(df_Cleanliness,index="member_id",columns="hotel_id",values="rating")

    df_service=df[['member_id','hotel_id']]
    df_service.insert(loc=2,column="rating",value=ratings_split[6])
    df_service["rating"]=pd.to_numeric(df_service["rating"].str.split(":").str[0])
    df_service=pd.pivot(df_service,index="member_id",columns="hotel_id",values="rating")
    dfs=[df_overall,df_value,df_rooms,df_service,df_location,df_Cleanliness,df_sleep_quality]
    return dfs

In [55]:
def load_dataset(path):
    df=pd.read_csv(path)
    df.drop(["review_text","review_id"],axis=1,inplace=True)
    df["rating"]=df["rating"].astype(str)
    df["recommend_list"]=df["recommend_list"].astype(str)
    df["ratings"]=df["rating"]+":Overall;"+df["recommend_list"]
    df.drop(["recommend_list","rating"],inplace=True,axis=1)
    df.drop_duplicates(subset=['hotel_id', 'member_id'], inplace=True,keep="first")
    # now lets do train test split
    print(df.shape)
    train,test=train_test_split(df,test_size=0.2)
    print(train.shape,test.shape)
    # now generating dataframes for each class 
    df_train=GenDataset(train)
    df_test=GenDataset(test)
    return df_train,df_test

In [56]:
df_train,df_test=load_dataset("./../TripAdvisor.csv")
# print(df_train[0].shape,df_test[0].shape)

(20401, 3)
(16320, 3) (4081, 3)

In [135]:
# df_overall.to_csv("./dataset/df_overall.csv")
# df_value.to_csv("./dataset/df_value.csv")
# df_Cleanliness.to_csv("./dataset/df_cleanliness.csv")
# df_location.to_csv("./dataset/df_location.csv")
# df_rooms.to_csv("./dataset/df_rooms.csv")
# df_service.to_csv("./dataset/df_service.csv")
# df_sleep_quality.to_csv("./dataset/df_sleep_quality.csv")

In [31]:
df_train[0].to_csv("./df_train.csv")
df_test[0].to_csv("./df_test.csv")

In [33]:
import pandas as pd
df=pd.read_csv("./../TripAdvisor.csv")

In [34]:
df=df[~df["recommend_list"].str.contains("check",case=False)]
df=df[~df["recommend_list"].str.contains("business",case=False)]
df.shape
df.to_csv("TripAdvisorClean.csv",index=False)

In [39]:
df=pd.read_csv("./TripAdvisorClean.csv")
df.head(10)

,review_id,member_id,hotel_id,rating,recommend_list,review_text
0,review_100005210,BD140084F7ECD3FC293E888ECB7DE217,Traders_Hotel_Singapore,5,5:Value;5:Location;5:Sleep Quality;5:Rooms;5:C...,Stayed here for 1 night en route to Australia....
1,review_100006218,BD140084F7ECD3FC293E888ECB7DE217,PARKROYAL_on_Kitchener_Road,5,5:Value;5:Location;5:Sleep Quality;5:Rooms;5:C...,"<span class=""bold_review"">Stayed here coming b..."
2,review_100015116,0051648FC0754F9E7117225BAF68773D,Premier_Inn_London_Southwark_Borough_Market,5,5:Value;5:Location;5:Sleep Quality;5:Rooms;5:C...,This was my third stay at Southwark and was ha...
3,review_100043459,14F9DD9816194FF75FDC26CC2B4D08D5,W_Hong_Kong,5,4:Value;4:Location;5:Sleep Quality;5:Rooms;5:C...,"We arrived early in HK, 8am straight from a lo..."
4,review_100099600,BF16241AA20DB4E9A6673F95285B1728,Hilton_London_Metropole,5,4:Value;4:Location;4:Sleep Quality;4:Rooms;5:C...,We have stayed at this hotel many times and th...
5,review_100105584,8DCF9BE7F5EAB3DE26B896DB3702D796,Crowne_Plaza_Chicago_Magnificent_Mile,4,4:Value;4:Location;4:Sleep Quality;4:Rooms;4:C...,this hotel is good. good location. good servic...
6,review_100110098,CB1E783A113D4A05709F3464ACCF9151,Club_Quarters_World_Trade_Center,4,5:Value;4:Location;5:Sleep Quality;4:Rooms;5:C...,"Located in lower Manhattan, one of the oldest ..."
7,review_100151542,FE1D836F1D36BAC74A16741C3AB728A9,DoubleTree_by_Hilton_London_West_End,4,5:Value;5:Location;5:Sleep Quality;5:Rooms;5:C...,i took my wife for her birthday and after read...
8,review_100171461,C53B04A2355FF8E9C255A1DE6A3C7095,Holiday_Inn_Express_New_York_City_Wall_Street,4,4:Value;3:Location;4:Sleep Quality;4:Rooms;4:C...,Neither wind nor rain or a brutal combination ...
9,review_100184487,CE4D5692C73F6A8A9FE6A35BB6EB8B61,The_Pierre_A_Taj_Hotel_New_York,2,1:Value;5:Location;4:Sleep Quality;1:Rooms;4:C...,The renovation took years and the result is ve...